AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  photob2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: photob2
  search-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos
      Handler: search-photos.lambda_handler
      Runtime: python3.8
      CodeUri: ./lambda_functions
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::105234542199:role/service-role/search-photos-role-xjsn2kbb'
      Environment:
        Variables:
          REGION: us-west-2
      Layers:
        - arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-requests:12
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /search
            Method: get

  index-photos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos
      Handler: index-photos.lambda_handler
      Runtime: python3.6
      CodeUri: ./lambda_functions
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::105234542199:role/service-role/index-photos-role-1ihj323z'
      Layers:
        - arn:aws:lambda:us-west-2:770693421928:layer:Klayers-python38-requests:12
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket:
              Ref: photob2
            Events: s3:ObjectCreated:Put
      Environment:
        Variables:
          REGION: us-west-2